spring:
  application:
    name: nowcoder-community
  servlet:
    session:
      cookie:
        path: /

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/community
    username: root
    password: 123456

  mail:
    host: smtp.qq.com
    port: 465
    username: 1348142849@qq.com
    from: 1348142849@qq.com
    password: mtcpscgflmgpjajg
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
  data:
    redis:
      database: 1
      host: 127.0.0.1
      password: 123456
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s

server:
  port: 8080
  servlet:
    context-path: /community

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    use-generated-keys: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zxp.nowcodercommunity.pojo

logging:
  level:
    root: info
# debug: true

community:
  path:
    domain: http://localhost:5173

jwt:
  header: Authorization
  # OpenSSL??
  secret: tFCj//rZC1P8Jp6qnKYjTsJVkLcS3MlrUdfodISg6VU34NvVFsulmHM8b3SXQw2gp9/8m1zAdhsAW1UFFvrSDw==
  expireTime: 60



